# Generated by Django 4.2 on 2024-04-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
