# Generated by Django 4.2 on 2024-05-09 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voters',
            field=models.ManyToManyField(related_name='voted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
